<?php

namespace MBLBundle\Repository;

/**
 * ChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRepository extends \Doctrine\ORM\EntityRepository
{

    public function myfindByProfil($user)
    {
        return $this ->createQueryBuilder('c')
            ->select('c')
            ->join('c.profils', 'pro')
            ->where('pro = :Profil')
            ->setParameter('Profil', $user)
            ->getQuery()
            ->getResult();// TODO: Change the autogenerated stub
    }
    public function myFindChatExist($currentUser, $connectedUser)
    {
        return $this ->createQueryBuilder('c')
            ->select('c')
            ->join('c.profils', 'pro')
            ->where('pro = :Profil1')
            ->setParameter('Profil1', $currentUser)
            ->andWhere('pro = :Profil2')
            ->setParameter('Profil2', $connectedUser)
            ->getQuery()
            ->getResult();// TODO: Change the autogenerated stub
    }


}
