<?php

namespace MBLBundle\Repository;

/**
 * CompetencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencesRepository extends \Doctrine\ORM\EntityRepository
{
}
