<?php

namespace MBLBundle\Repository;

/**
 * ConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionRepository extends \Doctrine\ORM\EntityRepository
{
}
