<?php

namespace MBLBundle\Repository;

/**
 * DispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispoRepository extends \Doctrine\ORM\EntityRepository
{
}
