<?php

namespace MBLBundle\Repository;

/**
 * ETQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ETQRepository extends \Doctrine\ORM\EntityRepository
{
}
