<?php

namespace MBLBundle\Repository;

/**
 * InvestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestRepository extends \Doctrine\ORM\EntityRepository
{
}
