<?php

namespace MBLBundle\Repository;

/**
 * MatchingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchingRepository extends \Doctrine\ORM\EntityRepository
{
}
