<?php

namespace MBLBundle\Repository;

/**
 * OuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuRepository extends \Doctrine\ORM\EntityRepository
{
}
