<?php

namespace MBLBundle\Repository;

/**
 * ProfilRechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRechercheRepository extends \Doctrine\ORM\EntityRepository
{
}
