<?php

namespace MBLBundle\Repository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindOneByChatId($texts_chat)
    {

        return $this ->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.datecreation', 'DESC')
            ->setMaxResults(10)
            ->join('t.chats', 'chat')
            ->where('chat.id = :chatId')
            ->setParameter('chatId', $texts_chat)
            ->getQuery()
            ->getResult()
            ;

    }

    public function myFindOneByChatIdViewer($texts_chat, $currentUser)
    {
        return $this ->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.datecreation', 'DESC')
            ->setMaxResults(10)
            ->join('t.chats', 'chat')
            ->where('chat.id = :chatId')
            ->setParameter('chatId', $texts_chat)
            ->andWhere('t.profil != :user')
            ->setParameter('user', $currentUser)
            ->getQuery()
            ->getResult()
            ;
    }
    public function myFindCountViews($currentId)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t.seen as tt', 't.profil as profil')
            ->join('t.chats', 'chat')
            ->join('chat.profils', 'pro')
            ->where('pro.id = :proId')
            ->setParameter('proId', $currentId)

        ;


        return $qb->getQuery()->getResult();
    }
}