<?php

namespace MBLBundle\Repository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindOneByChatId($texts_chat)
    {

        return $this ->createQueryBuilder('t')
            ->select('t')
            ->orderBy('t.datecreation', 'DESC')
            ->setMaxResults(10)
            ->join('t.chats', 'chat')
            ->where('chat.id = :chatId')
            ->setParameter('chatId', $texts_chat)
            ->getQuery()
            ->getResult()
            ;

    }
}