<?php

namespace MBLBundle\Repository;

/**
 * TypeDeProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDeProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTypeDeProjetByLocale($locale)
    {
        return $this->createQueryBuilder('t')
            ->select('t.typeDeProjet' . $locale)
            ;
    }
}
