MBLBundle\Entity\Dispo:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\DispoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dispofr:
            type: string
            length: 255
        dispoit:
            type: string
            length: 255

    oneToMany:
        profils:
            targetEntity: MBLBundle\Entity\Profil
            mappedBy: dispo

        profilrecherches:
            targetEntity: MBLBundle\Entity\ProfilRecherche
            mappedBy: dispo