MBLBundle\Entity\Secteur:
    type: entity
    table: null
    repositoryClass: MBLBundle\Repository\SecteurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        secteurActivitefr:
            type: string
            length: 255
        secteurActiviteit:
            type: string
            length: 255

    oneToMany:
        projets:
            targetEntity: MBLBundle\Entity\Projet
            mappedBy: secteur
            cascade: ["persist"]