imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MBLBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    upload_directory: '%kernel.root_dir%/web/uploads/images'

framework:
    #esi: ~
    translator: { fallbacks: ["%locale%"] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: %locale%
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: MBLBundle\Entity\Profil
    from_email:
        address: flo@gmail.com
        sender_name: flo

    registration:
        form:
            type: MBLBundle\Form\RegistrationType
        confirmation:
            enabled: false
            template:   '@FOSUser/Registration/email.txt.twig'

    resetting:
        email:
            template:    '@FOSUser/Resetting/email.txt.twig'

    service:
        mailer: fos_user.mailer.twig_swift


easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i'
    entities:
        Competences:
            class: MBLBundle\Entity\Competences
            form:
                fields: ['competencesfr','competencesit']

        Dispo:
            class: MBLBundle\Entity\Dispo
            form:
                fields: ['dispofr','dispoit']

        ETQ:
            class: MBLBundle\Entity\ETQ
            form:
                fields: ['etqfr','etqit']

        Invest:
            class: MBLBundle\Entity\Invest
            form:
                fields: ['investfr','investit']

        Metier:
            class: MBLBundle\Entity\Metier
            form:
                fields: ['metierfr','metierit']

        Ou:
            class: MBLBundle\Entity\Ou
            form:
                fields: ['ouit','oufr']

        Profil:
            class: MBLBundle\Entity\Profil
            disabled_actions: ['new']
            list:
                fields:
                    - nom
                    - prenom
                    - email
                    - description
                    - linkedIn
                    - localisation
                    - lng
                    - ville
                    - etq
                    - dispo
                    - ou
                    - metier
                    - invest
                    - { property: 'competences', type: 'array' }
                    - { property: 'projets', type: 'array' }
                    - enabled
                    - lastLogin
                    - { property: 'roles', type: 'array' }
            edit:
                fields:
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        ProfilRecherche:
            class: MBLBundle\Entity\ProfilRecherche
            disabled_actions: ['new', 'edit']
            list:
                fields:
                    - etq
                    - ou
                    - invest
                    - dispo
                    - metier
                    - { property: 'projets', type: 'array' }
                    - { property: 'competences', type: 'array' }

        Projet:
            class: MBLBundle\Entity\Projet
            disabled_actions: ['new', 'edit']
            list:
                fields:
                    - titrefr
                    - titreit
                    - descriptionfr
                    - descriptionit
                    - siteInternetfr
                    - siteInternetit
                    - ebustaUrlfr
                    - ebustaUrlit
                    - localisation
                    - dateCreation
                    - ville
                    - lngp
                    - secteur
                    - typeDeProjet
                    - { property: 'profilsrecherches', type: 'array' }
                    - { property: 'profils', type: 'array' }

        Secteur:
            class: MBLBundle\Entity\Secteur
            form:
                fields: ['secteurActivitefr','secteurActiviteit']

        TypeDeProjet:
            class: MBLBundle\Entity\TypeDeProjet
            form:
                fields: ['typeDeProjetfr','typeDeProjetit']

    site_name: "Innova'Up"
    design:
        brand_color: '#98d4e1'
        color_scheme: 'light'

lexik_translation:
    fallback_locale: ["%locale%"]         # (required) default locale(s) to use
    managed_locales: [fr, it] # (required) locales that the bundle has to manage