mbl_homepage:
    path:     /
    defaults: { _controller: MBLBundle:User:index }

homepageProfil:
    path: /homepageProfil
    defaults: { _controller: MBLBundle:User:homepageProfil }

editProfil:
    path: /editProfil
    defaults: { _controller: MBLBundle:User:editProfil }

#deleteProfil:
#    path: /delete
#    defaults: { _controller: "MBLBundle:User:delete"}
#    methods:  DELETE

showProfil:
    path: /showProfil/{id}
    defaults: { _controller: MBLBundle:User:showProfil }

showMyProfil:
    path: /showMyProfil
    defaults: { _controller: MBLBundle:User:showMyProfil }

showAllProfils:
    path: /showAllProfils/{page}
    defaults:
        _controller: MBLBundle:User:showAllProfils
        page: null

createProjet:
    path: /createProject
    defaults: { _controller: MBLBundle:User:createProject }

editProjet:
    path: /editProject/{id}
    defaults: { _controller: MBLBundle:User:editProject }

#Création, édition, delete PROFIL RECHERCHER
createProfilRechercheProjet:
    path: /createProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:createProfilRechercheProject
        id: null

newProfilRechercheProjet:
    path: /newProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:newProfilRechercheProject
        id: null

editProfilRechercheProjet:
    path: /editProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:editProfilRechercheProject
        id: null

deleteProfilRechercheProjet:
    path: /deleteProfilRecherche/{id}
    defaults:
        _controller: MBLBundle:User:deleteProfilRecherche

deleteProfilRerchercheProjet:
    path: /deleteProfil
    defaults: { _controller: MBLBundle:User:deleteProfilR}

showProject:
    path: /showProject/{page}
    defaults:
        _controller: MBLBundle:User:showProject
        page: null

showOneProject:
    path: /showOneProject/{id}
    defaults: { _controller: MBLBundle:User:showOneProject }

showMyProject:
    path: /showMyProject
    defaults: { _controller: MBLBundle:User:showMyProject }

deleteMyProject:
    path: /deleteMyProject/{id}
    defaults: { _controller: MBLBundle:User:deleteMyProject }


testTraduction:
    path: /test/{name}
    defaults: { _controller: MBLBundle:User:traduction }

chatIndex:
    path: /chatIndex/{id}
    defaults:
        _controller: MBLBundle:User:chatIndex
        id: null

chatConnect:
    path: /chatConnect/{id}
    defaults: { _controller: MBLBundle:User:chatConnect}
    methods: GET

connect:
    path: /connect/{id}
    defaults:
        _controller: MBLBundle:User:connect
        id: null

chatDisconnect:
    path: /chatDisconnect/{id}
    defaults: { _controller: MBLBundle:User:chatDisconnect}
    methods: GET

#Routing for footer links
apropos:
    path: /apropos
    defaults:
        _controller: FrameworkBundle:Template:template
        template: MBLBundle:Templates:apropos.html.twig

legal:
    path: /legal
    defaults:
        _controller: FrameworkBundle:Template:template
        template: MBLBundle:Templates:legal.html.twig

presse:
    path: /presse
    defaults:
        _controller: FrameworkBundle:Template:template
        template: MBLBundle:Templates:presse.html.twig

contact:
    path: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template: MBLBundle:Templates:contact.html.twig

conseils:
    path: /conseils
    defaults:
        _controller: FrameworkBundle:Template:template
        template: MBLBundle:Templates:conseils.html.twig


# Cette route doit rester la dernière
#remove_trailing_slash:
#    path: /{url}
#    defaults: { _controller: MBLBundle:Redirecting:removeTrailingSlash }
#    requirements:
#        url: .*/$
#    methods: [GET]





