mbl_homepage:
    path:     /
    defaults: { _controller: MBLBundle:User:index }

homepageProfil:
    path: /homepageProfil
    defaults: { _controller: MBLBundle:User:homepageProfil }

editProfil:
    path: /editProfil
    defaults: { _controller: MBLBundle:User:editProfil }

#deleteProfil:
#    path: /delete
#    defaults: { _controller: "MBLBundle:User:delete"}
#    methods:  DELETE

showProfil:
    path: /showProfil
    defaults: { _controller: MBLBundle:User:showProfil }

showAllProfils:
    path: /showAllProfils
    defaults: { _controller: MBLBundle:User:showAllProfils }


createProfil:
    path: /createProfil
    defaults: { _controller: MBLBundle:User:createProfil }

createProjet:
    path: /createProject
    defaults: { _controller: MBLBundle:User:createProject }

editProjet:
    path: /editProject/{id}
    defaults: { _controller: MBLBundle:User:editProject }

createProfilRechercheProjet:
    path: /createProfilRechercheProject/{id}
    defaults:
        _controller: MBLBundle:User:createProfilRechercheProject
        id: null

showProject:
    path: /showProject
    defaults: { _controller: MBLBundle:User:showProject }

showMyProject:
    path: /showMyProject
    defaults: { _controller: MBLBundle:User:showMyProject }



